In [1]:
print("""
@Title: 交互式神经网络
@Author(s): Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime: 2023-09-13 00:32:40
@Description: 
""")


@Title: 交互式神经网络
@Author(s): Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime: 2023-09-13 00:32:40
@Description: 



In [2]:
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
np.random.seed(1)
plt.style.use("ggplot")
plt.rcParams["savefig.dpi"] = 300
plt.rcParams["font.family"] = "serif"
np.set_printoptions(suppress=True)

## 张量和张量运算

In [4]:
# 标量张量
t0 = np.array(10)
t0

array(10)

In [12]:
# 向量张量
t1 = np.array((2, 1))
t1

array([2, 1])

In [7]:
# 矩阵张量
t2 = np.arange(10).reshape(5, 2)
t2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [8]:
# 三阶张量
t3 = np.arange(16).reshape(2, 4, 2)
t3

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

在神经网络中，张量上的几个数学运算很重要，比如逐元素运算或点积

In [9]:
t2 + 1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [10]:
t2 + t2

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [13]:
t1

array([2, 1])

In [14]:
t2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [15]:
np.dot(t2, t1)

array([ 1,  7, 13, 19, 25])

In [18]:
np.dot(t1, t2.T)
# 感觉运行的逻辑很奇怪，t1 是一个向量，可行向量？可列向量？

array([ 1,  7, 13, 19, 25])

In [19]:
t2[:, 0] * 2 + t2[:, 1] * 1

array([ 1,  7, 13, 19, 25])

In [23]:
2 * t2.T[0, :] + 1 * t2.T[1, :]

array([ 1,  7, 13, 19, 25])