In [1]:
print("""
@Title: 期权定价的数值方法
@Author(s): Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime: 2023-10-22 15:23:18
@Description: 
""")


@Title: 期权定价的数值方法
@Author(s): Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime: 2023-10-22 15:23:18
@Description: 



# 期权定价的数值方法

## 欧式期权定价

In [2]:
import math
r = .05
T = 2
t = T/2
u = 1.2
d = .8

q = (math.exp(r*t) - d)/(u-d)
print('q =', q)

q = 0.6281777409400603


## 编写 StockOption 基类

In [3]:
from stockoption import BinomialEuropeanOption

In [4]:
eu_option = BinomialEuropeanOption(
    50, 52, r=0.05, T=2, N=2, pu=0.2, pd=0.2, is_put=True)
print('European put option price is:', eu_option.price())

European put option price is: 4.1926542806038585


In [5]:
eu_option.STs

array([72., 48., 32.])

In [6]:
eu_option.init_payoffs_tree()

array([ 0.,  4., 20.])

In [7]:
eu_option.K

52

In [8]:
import numpy as np
np.maximum(0, eu_option.STs - eu_option.K)

array([20.,  0.,  0.])

In [9]:
eu_option.init_payoffs_tree()

array([ 0.,  4., 20.])

In [10]:
eu_option.begin_tree_traversal()

array([4.19265428])

In [12]:
[np.array([19]), np.array([20]), np.array([21]), np.array([22])]

[array([19]), array([20]), array([21]), array([22])]