In [1]:
import pandas as pd
import numpy as np

In [2]:
arr = np.array(range(12)).reshape(2, -1)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [3]:
np.delete(arr, [2, 3, 5], axis=1)

array([[ 0,  1,  4],
       [ 6,  7, 10]])

In [4]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [5]:
arr.shape[1]

6

In [6]:
from mfpr import add_row, add_column

In [7]:
add_row(arr, 3)

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [8]:
add_column(arr, 5)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 6.,  7.,  8.,  9., 10., 11.,  0.,  0.,  0.,  0.,  0.]])

In [10]:
arr[1:]

array([[ 6,  7,  8,  9, 10, 11]])

In [11]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [12]:
import pandas as pd

In [13]:
pd.DataFrame(arr)

0  1  2  3   4   5
0  0  1  2  3   4   5
1  6  7  8  9  10  11

In [47]:
import yfinance as yf
df = yf.download('AAPL', start='2023-01-01')

[*********************100%***********************]  1 of 1 completed


In [48]:
df

Open        High         Low       Close   Adj Close  \
Date                                                                     
2023-01-03  130.279999  130.899994  124.169998  125.070000  124.374794   
2023-01-04  126.889999  128.660004  125.080002  126.360001  125.657639   
2023-01-05  127.129997  127.769997  124.760002  125.019997  124.325081   
2023-01-06  126.010002  130.289993  124.889999  129.619995  128.899506   
2023-01-09  130.470001  133.410004  129.889999  130.149994  129.426544   
...                ...         ...         ...         ...         ...   
2023-12-22  195.179993  195.410004  192.970001  193.600006  193.600006   
2023-12-26  193.610001  193.889999  192.830002  193.050003  193.050003   
2023-12-27  192.490005  193.500000  191.089996  193.149994  193.149994   
2023-12-28  194.139999  194.660004  193.169998  193.580002  193.580002   
2023-12-29  193.899994  194.399994  191.729996  192.529999  192.529999   

               Volume  
Date                   
2023-01-03  112117500  
2023-01-04   89113600  
2023-01-05   80962700  
2023-01-06   87754700  
2023-01-09   70790800  
...               ...  
2023-12-22   37122800  
2023-12-26   28919300  
2023-12-27   48087700  
2023-12-28   34049900  
2023-12-29   42628800  

[250 rows x 6 columns]

In [49]:
a = (df['Low'] < df['Low'].shift(5)) & (df['Low'] < df['Low'].shift(
        13)) & (df['Low'] > df['Low'].shift(21))

In [29]:
a.sum()

13

In [30]:
b = df['Close'] > df['Close'].shift(3)

In [35]:
(b & a).astype(int).sum()

1

In [50]:
df.loc[a, 'long'] = 1

In [43]:
~a - 1

Date
2023-01-03    0
2023-01-04    0
2023-01-05    0
2023-01-06    0
2023-01-09    0
             ..
2023-12-22    0
2023-12-26    0
2023-12-27   -1
2023-12-28   -1
2023-12-29    0
Name: Low, Length: 250, dtype: int32

In [52]:
df['long'] = df['long'].fillna(0)

In [56]:
(a & b).astype(int).sum()

1